### ISSUE TITLE
[BITE] Before&After 상세 페이지 구현

### ISSUE THREAD

**Issue by kim-jingyu** [2nnerPeace/The-Moon-Ha-Android#9]
## 🍀 Description
문화 한 입의 Before&After 상세 페이지를 구현합니다.

## ✅ Todo
- [x] 리스트 페이지에서 상세보기 페이지로 이동하는 기능 구현
- [x] 상세보기 페이지 Design UI 구현
- [x] 상세보기 페이지 기능 구현

## ETC
